export const plans = [
  {
    background: 1,
    short: true,
    usd: false,
    title: "MASA MUSCULAR",
    price: 33000,
    benefits: [
      "Más musculo y menos grasa",
      "Definición muscular y tonificación",
      "Aumento de fuerza y resistencia",
      "Físico atletico, definido y tonificado",
    ],
    includes: [
      "Plan de entrenamiento personalizado",
      "Plan de alimentación personalizado",
      "+150 recetas fit",
      "Seguimiento y motivación",
      "Comunidad por WhatsApp",
      "Mentorías semanales en VIVO",
    ],
  },
  {
    background: 2,
    short: true,
    usd: false,
    title: "QUEMAR GRASA Y TONIFICAR",
    price: 33000,
    benefits: [
      "Chau grasa e inflamación",
      "Aumento de energía",
      "Tonificación y abdominales",
      "Mayor autoestima",
      "Mejor calce de ropa",
      "Más confianza y presencia",
    ],
    includes: [
      "Plan de entrenamiento personalizado",
      "Plan de alimentación personalizado",
      "+150 recetas fit",
      "Seguimiento y motivación",
      "Comunidad por WhatsApp",
      "Mentorías semanales en VIVO",
    ],
  },
  // {
  //   background: 3,
  //   short: true,
  //   usd: true,
  //   title: "ASESORIA 1-1",
  //   price: 200,
  //   includes: [
  //     "Entrevista 1-1 conmigo",
  //     "Consulta nutricional online con Lic. Juan Elias Perez",
  //     "Reportes diarios, semanales y mensuales",
  //     "Seguimiento 24/7 por WhatsApp",
  //     "Llamadas semanales individuales",
  //     "Grupo Whatsapp VIP",
  //     "Mentorías semanales en VIVO",
  //   ],
  // },
];
